---
title: "Machine Learning"
author: "LK"
date: "21 June 2015"
output: html_document
---
Load the caret library and read the trainign data file
```{r}
library(caret)        
set.seed(1234)

        wd<-"C:/Users/lnkkota.Home-PC/datasciencecoursera/MachineLearning"
        if (!is.null(wd)) setwd(wd)

rawdata <- read.csv("pml-training.csv", na.strings=c("NA",""),strip.white = T)
dim(rawdata)

isNA <- apply(rawdata, 2, function(x) { sum(is.na(x)) })
validData <- subset(rawdata[, which(isNA == 0)],
                    select=-c(X, user_name, new_window, num_window, raw_timestamp_part_1, raw_timestamp_part_2, cvtd_timestamp))

dim(validData)

inTrain <- createDataPartition(validData$classe, p=0.7, list=F)
training <- validData[inTrain,]
testing <- validData[-inTrain,]
       
 
```

Train the model - Random Forest Model

```{r, echo=FALSE}
ctrl <- trainControl(allowParallel=T, method="cv", number=4)
model <- train(classe ~ ., data=training, model="rf", trControl=ctrl)
pred <- predict(model, newdata=testing)

```

Check the prediction

```{r, echo=TRUE}
sum(pred == testing$classe) / length(pred)

confusionMatrix(testing$classe, pred)$table

rawTestData <- read.csv("pml-testing.csv", na.strings=c("NA",""), strip.white=T)
validTestData <- subset(rawTestData[, which(isNA == 0)], 
                        select=-c(X, user_name, new_window, num_window, raw_timestamp_part_1, raw_timestamp_part_2, cvtd_timestamp))
predict(model, newdata=validTestData)
```
